// src/utils/pptxGenerator.js

import PptxGenJS from 'pptxgenjs';
import * as FileSystem from 'expo-file-system/legacy';

/**
 * Generates a PowerPoint (.pptx) file.
 * Features: Dark Mode support, Slide Masters, and Overflow Protection for Transcripts.
 */
export const generatePPTX = async (data, t, theme) => {
    // 1. Setup PPTX
    const pres = new PptxGenJS();
    
    // --- THEME SETTINGS ---
    const isDark = theme === 'dark';
    const bgColor = isDark ? "000000" : "FFFFFF"; // Arka Plan
    const textColor = isDark ? "FFFFFF" : "000000"; 
    const accentColor = "4A90E2"; // Mavi (Başlıklar)
    const secondaryColor = "888888"; // Gri (Footer)

    // 2. Define Master Slide (TEMA AYARI)
    // Bu ayar, tüm slaytların arka planını kilitler.
    pres.defineSlideMaster({
        title: "MASTER_SLIDE",
        background: { color: bgColor }, 
        objects: [
            // Footer (Sayfa Numarası ve İmza) - En altta %92 konumunda
            {
                text: { 
                    text: "Generated by DiarizeAI", 
                    options: { x: 0.5, y: "95%", w: "90%", align: "center", color: secondaryColor, fontSize: 10 } 
                }
            }
        ],
        slideNumber: { x: "95%", y: "95%", color: accentColor, fontSize: 10 }
    });

    // --- SLIDE 1: TITLE (Kapak) ---
    const slide1 = pres.addSlide({ masterName: "MASTER_SLIDE" });
    
    slide1.addText(data.originalName || "Audio Analysis", {
        x: 0.5, y: "40%", w: "90%",
        fontSize: 32, bold: true, align: "center",
        color: accentColor
    });

    slide1.addText(`${t('label_language')}: ${data.language || "-"}  |  ${t('label_type')}: ${data.conversation_type || "-"}`, {
        x: 0.5, y: "55%", w: "90%",
        fontSize: 14, align: "center",
        color: textColor
    });

    // --- SLIDE 2: SUMMARY (Özet) ---
    const slide2 = pres.addSlide({ masterName: "MASTER_SLIDE" });
    
    slide2.addText(t('label_summary'), {
        x: 0.5, y: 0.5, w: "90%", h: 0.5,
        fontSize: 24, bold: true, color: accentColor
    });

    slide2.addText(data.summary || "", {
        x: 0.5, y: 1.1, w: "90%", h: "75%",
        fontSize: 14, color: textColor,
        valign: "top"
    });

    // --- SLIDE 3: KEY POINTS (Anahtar Noktalar) ---
    if (data.keypoints_json || data.keypoints) {
        let points = [];
        try {
            let src = data.keypoints_json || data.keypoints;
            points = typeof src === 'string' ? JSON.parse(src) : src;
        } catch (e) { points = []; }

        if (Array.isArray(points) && points.length > 0) {
            const slide3 = pres.addSlide({ masterName: "MASTER_SLIDE" });
            
            slide3.addText(t('label_keypoints'), {
                x: 0.5, y: 0.5, w: "90%", h: 0.5,
                fontSize: 24, bold: true, color: accentColor
            });

            // Maddeleri ekle
            points.forEach((point, index) => {
                // Maksimum 8 madde sığdır, taşarsa kes (basit koruma)
                if (index < 8) {
                    slide3.addText(point, {
                        x: 0.5, y: 1.1 + (index * 0.6), w: "90%", h: 0.5,
                        fontSize: 14, color: textColor,
                        bullet: { type: "bullet", color: accentColor } 
                    });
                }
            });
        }
    }

    // --- SLIDES 4+: TRANSCRIPT (Akıllı Sayfalama & Taşma Koruması) ---
    if (data.segments || data.segments_json) {
        let segments = [];
        try {
            let source = data.segments || data.segments_json;
            if (Array.isArray(source)) segments = source;
            else if (typeof source === 'string') segments = JSON.parse(source);
        } catch (e) {}

        if (Array.isArray(segments)) {
            // AYARLAR:
            const ITEMS_PER_SLIDE = 4; // Her slayta MAX 4 konuşma (Güvenli alan)
            const START_Y = 1.0;       // Başlangıç yüksekliği (inç)
            const BLOCK_HEIGHT = 1.1;  // Her bloğun kapladığı alan (inç)
            
            // Toplam kaç sayfa olacağını hesapla
            const totalPages = Math.ceil(segments.length / ITEMS_PER_SLIDE);

            for (let i = 0; i < segments.length; i += ITEMS_PER_SLIDE) {
                // Mevcut sayfanın verilerini al (Chunk)
                const chunk = segments.slice(i, i + ITEMS_PER_SLIDE);
                const slideTr = pres.addSlide({ masterName: "MASTER_SLIDE" });
                const pageNum = Math.floor(i / ITEMS_PER_SLIDE) + 1;

                // Başlık
                slideTr.addText(`${t('label_transcript')} (${pageNum}/${totalPages})`, {
                    x: 0.5, y: 0.4, w: "90%", h: 0.5,
                    fontSize: 18, bold: true, color: accentColor
                });

                // Segmentleri Ekle
                chunk.forEach((seg, idx) => {
                    // Dinamik Y Konumu Hesaplama
                    // Başlık (0.4) + Başlangıç (1.0) + (Sıra * Blok Yüksekliği)
                    const currentY = START_Y + (idx * BLOCK_HEIGHT);
                    const timeStr = formatTime(seg.start || seg.start_time);

                    // 1. İsim ve Süre (Tek Satır)
                    slideTr.addText(`${seg.speaker || "Speaker"} [${timeStr}]`, {
                        x: 0.5, 
                        y: currentY, 
                        w: "90%", 
                        h: 0.3, // İsim yüksekliği
                        fontSize: 12, 
                        bold: true, 
                        color: accentColor
                    });

                    // 2. Konuşma Metni (Altına)
                    slideTr.addText(seg.text, {
                        x: 0.5, 
                        y: currentY + 0.3, // İsmin hemen altı
                        w: "90%", 
                        h: 0.7, // Metin kutusu yüksekliği
                        fontSize: 12, 
                        color: textColor,
                        italic: true,
                        valign: "top" // Kutunun tepesinden başla
                    });
                });
            }
        }
    }

    // 3. Dosya Oluştur
    const base64 = await pres.write("base64");
    return base64;
};

// Yardımcı: Süre Formatlayıcı
const formatTime = (seconds) => {
    if (!seconds) return "00:00";
    const totalSeconds = Math.floor(seconds);
    const minutes = Math.floor(totalSeconds / 60);
    const secs = totalSeconds % 60;
    return `${minutes}:${secs < 10 ? '0' : ''}${secs}`;
};