// src/utils/wordGenerator.js

import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle, ShadingType } from 'docx';

export const generateWord = async (data, t, theme) => {
    const isDark = theme === 'dark';
    
    // --- RENK AYARLARI ---
    const textColor = isDark ? "FFFFFF" : "000000"; 
    const accentColor = "4A90E2"; 

    // Tablo Hücresi Dolgusu (Siyah Zemin)
    const cellShading = isDark ? {
        fill: "000000",
        val: ShadingType.CLEAR,
        color: "auto"
    } : undefined;

    // --- YARDIMCI FONKSİYONLAR ---

    const createText = (text, options = {}) => {
        return new TextRun({
            text: text,
            color: textColor,
            font: "Helvetica",
            size: 24, 
            ...options
        });
    };

    const createPara = (children, alignment = AlignmentType.LEFT, spacing = { after: 120 }) => {
        return new Paragraph({
            alignment: alignment,
            spacing: spacing,
            children: children
        });
    };

    const createHeading = (text) => {
        return new Paragraph({
            heading: HeadingLevel.HEADING_2,
            alignment: AlignmentType.LEFT,
            spacing: { before: 400, after: 200 },
            children: [
                new TextRun({
                    text: text,
                    bold: true,
                    color: accentColor,
                    size: 32, 
                }),
            ],
        });
    };

    const createBullet = (text) => {
        return new Paragraph({
            bullet: { level: 0 },
            children: [createText(text)],
        });
    };

    // --- İÇERİK BLOKLARI ---
    const contentBlocks = [];

    // Başlık
    contentBlocks.push(
        new Paragraph({
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { after: 300 },
            children: [
                new TextRun({
                    text: data.originalName || "Audio Analysis",
                    bold: true,
                    color: accentColor,
                    size: 48, 
                }),
            ],
        })
    );

    // Bilgiler
    contentBlocks.push(createPara([createText(`${t('label_language')}: ${data.language || "-"}`, { bold: true })]));
    contentBlocks.push(createPara([createText(`${t('label_type')}: ${data.conversation_type || "-"}`, { bold: true })]));
    
    contentBlocks.push(createPara([], AlignmentType.LEFT, { after: 200 })); // Boşluk

    // Özet
    contentBlocks.push(createHeading(t('label_summary')));
    contentBlocks.push(createPara([createText(data.summary || "")]));

    // Anahtar Noktalar
    if (data.keypoints_json || data.keypoints) {
        contentBlocks.push(createHeading(t('label_keypoints')));
        let points = [];
        try {
            let src = data.keypoints_json || data.keypoints;
            points = typeof src === 'string' ? JSON.parse(src) : src;
        } catch (e) { points = []; }

        if (Array.isArray(points)) {
            points.forEach(point => {
                contentBlocks.push(createBullet(point));
            });
        }
    }

    // Transkript
    if (data.segments || data.segments_json) {
        contentBlocks.push(createHeading(t('label_transcript')));
        
        let segments = [];
        let source = data.segments || data.segments_json;
        try {
            if (Array.isArray(source)) segments = source;
            else if (typeof source === 'string') segments = JSON.parse(source);
        } catch (e) {}

        if (Array.isArray(segments)) {
            segments.forEach(seg => {
                const timeStr = ` [${formatTime(seg.start || seg.start_time)}]`;
                
                contentBlocks.push(
                    new Paragraph({
                        spacing: { before: 200 },
                        children: [
                            new TextRun({
                                text: (seg.speaker || "Speaker") + timeStr,
                                bold: true,
                                color: accentColor,
                                size: 20, 
                            }),
                        ],
                    })
                );
                contentBlocks.push(createPara([createText(seg.text)]));
            });
        }
    }

    // Footer
    contentBlocks.push(
        new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { before: 600 },
            children: [
                new TextRun({
                    text: `Generated by DiarizeAI - ${new Date().toLocaleString()}`,
                    italics: true,
                    color: "888888",
                    size: 16,
                }),
            ],
        })
    );

    // --- TABLO & SAYFA DÜZENİ ---
    let finalChildren = [];
    
    // Sayfa Kenar Boşlukları (Margins)
    // Koyu modda kenar boşluğunu 0 yapıyoruz ki beyaz çerçeve kalmasın.
    // Açık modda standart boşluk bırakıyoruz.
    const pageMargins = isDark ? {
        top: 0,
        right: 0,
        bottom: 0,
        left: 0
    } : {
        top: 1000,
        right: 1000,
        bottom: 1000,
        left: 1000
    };

    if (isDark) {
        // KOYU MOD:
        // Sayfa kenarları 0 olduğu için, metinlerin kenara yapışmasını engellemek adına
        // tablonun İÇİNE margin (padding) veriyoruz. (1440 DXA = 1 inç civarı)
        const table = new Table({
            width: {
                size: 100, 
                type: WidthType.PERCENTAGE, 
            },
            // A4 genişliği ~11906 DXA. Kenar boşluğu 0 olduğu için tabloyu tam genişliğe zorluyoruz.
            columnWidths: [11906], 
            rows: [
                new TableRow({
                    children: [
                        new TableCell({
                            children: contentBlocks,
                            shading: cellShading,    // SİYAH ZEMİN
                            borders: {               // KENARLIK YOK
                                top: { style: BorderStyle.NONE, size: 0, color: "000000" },
                                bottom: { style: BorderStyle.NONE, size: 0, color: "000000" },
                                left: { style: BorderStyle.NONE, size: 0, color: "000000" },
                                right: { style: BorderStyle.NONE, size: 0, color: "000000" },
                            },
                            // İÇ BOŞLUK (PADDING) - Beyaz kenarlık yerine siyah iç boşluk
                            margins: {
                                top: 1440,    // ~2.5 cm üstten boşluk
                                bottom: 1440, // ~2.5 cm alttan boşluk
                                left: 1000,   // Sol boşluk
                                right: 1000   // Sağ boşluk
                            }
                        }),
                    ],
                }),
            ],
        });
        finalChildren = [table];
    } else {
        // AÇIK MOD
        finalChildren = contentBlocks;
    }

    // --- BELGE OLUŞTURMA ---
    const doc = new Document({
        background: {
            color: isDark ? "000000" : "FFFFFF",
        },
        sections: [{
            properties: {
                page: {
                    margin: pageMargins, // Dinamik kenar boşluğu (0 veya normal)
                },
            },
            children: finalChildren,
        }],
    });

    const buffer = await Packer.toBase64String(doc);
    return buffer;
};

const formatTime = (seconds) => {
    if (!seconds) return "00:00";
    const totalSeconds = Math.floor(seconds);
    const minutes = Math.floor(totalSeconds / 60);
    const secs = totalSeconds % 60;
    return `${minutes}:${secs < 10 ? '0' : ''}${secs}`;
};